language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
addons:
  apt:
    packages:
      - libgtk-3-dev
    update: true
os:
  - linux
  - osx
  - windows
script:
  - cargo build --verbose --release --features gui