#![windows_subsystem = "windows"]

[package]
name = "blackhole"
version = "1.0.0"
authors = ["William Venner <william@venner.io>"]
edition = "2018"
repository = "https://github.com/WilliamVenner/blackhole"
license = "MIT"
keywords = ["blackhole", "black hole", "forget", "ramdisk", "organization", "organisation", "organisation-tool", "organization-tool", "black-hole"]

[features]
gui = ["msgbox"]

[dependencies]
dirs = "3.0"
trash = "1.2"
msgbox = { version = "0.6.0", optional = true }

[target.'cfg(windows)'.dependencies]
powershell_script = "0.1"
winapi = { version = "0.3", features = ["winuser"] }
rust-ini = "0.16"
winreg = "0.8"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"