name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux_cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  
  build_linux_gui:
    needs: build_linux_cli
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install GUI
      run: sudo apt-get update && sudo apt-get install libgtk-3-dev -y
    - name: Build
      run: cargo build --verbose --features gui
  
  build_windows_cli:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        RUSTFLAGS: -Ctarget-feature=+crt-static
      run: cargo build --verbose
  
  build_windows_gui:
    needs: build_windows_cli
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        RUSTFLAGS: -Ctarget-feature=+crt-static
      run: cargo build --verbose --features gui
  
  build_macos_cli:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  
  build_macos_gui:
    needs: build_macos_cli
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features gui
